### ISSUE TITLE
Upload new version to ansible galaxy

### ISSUE THREAD

**Issue by pugnacity** [nginxinc/ansible-collection-nginx#2]
**Describe the bug**
Currently only the release 0.2.0 is available on the galaxy

**Comment by alessfg** [comment]
Right, that's the latest release so far. I will wrap up a new release with the latest changes as soon as I can.

**Comment by alessfg** [comment]
Pushed the latest release/changes to Ansible Galaxy/Automation Hub https://galaxy.ansible.com/nginxinc/nginx_core @pugnacity
